apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: app
data:
  node_env: development
  port: "4000"
  client_urls: http://localhost:3000
  better_auth_url: http://localhost:4000
