apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: app
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-for-auth-job
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              echo "⏳ Waiting for auth-job to complete..."
              while true; do
                status=$(kubectl get job auth-job -n app -o jsonpath='{.status.succeeded}')
                if [ "$status" = "1" ]; then
                  echo "✅ auth-job completed!"
                  break
                fi
                echo "…still waiting for auth-job"
                sleep 3
              done

      containers:
        - name: auth
          image: ghcr.io/awwwkshay/node-ts-auth-starter
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: node_env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: port
            - name: CLIENT_URLS
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: client_urls
            - name: BETTER_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: better_auth_url
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: better_auth_secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: database_url
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
