apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: app
type: Opaque
data:
  better_auth_secret: NTU5OTY4N2U2MzkyNjNiMDE5MmRmMDVjYmM2ZGNjMzZiMjM2NmYxZmQ4NjM3ZDllMzQzZTQ0ODI5ZmY4MGRmMQ==
  database_url: cG9zdGdyZXM6Ly9wb3N0Z3JlczpBa3NoYXlAMTIzQHBvc3RncmVzOjU0MzIvYXV0aA==
