apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres
  POSTGRES_PASSWORD: QWtzaGF5QDEyMw== # Akshay@123
  POSTGRES_MULTIPLE_DATABASES: YXBwLGF1dGg= # app,auth
